export type ChapitreTheorie = {
  titre: string;
  points: string[];
  exercices: string[];
};

// Contenu recopié tel quel de l'onglet Excel "THÉORIE  WORD" fourni par la
// direction — sert de référence rapide pour remplir le champ "Théorie
// donnée" des feuilles de route.
export const CHAPITRES_THEORIE_WORD: ChapitreTheorie[] = [
  { titre: "1er chapitre : (Page 1 à 7)", points: ["NOTIONS ÉLÉMENTAIRES ET TERMINOLOGIES", "La souris, sélection de texte, touches du clavier", "Fenêtre de l'enregistrement, les onglets et les rubans", "Ouvrir et enregistrement, barre d'outils accès rapide"], exercices: ["Exercice 1 (P5-6-7)"] },
  { titre: "2e chapitre : (Page 8 à 15)", points: ["CRÉER UN DOSSIER, ENREGISTREMENT, NOTIONS DE BASE", "Créer un dossier, effacement, annulation, répéter dernière opération", "Point d'insertion, style Normal et sans interligne", "Alinéa, alignement", "OUVERTURE ET ENREGISTREMENT", "Déplacement, insérer saut de page", "Convertir fichier", "Document récent, modèle prédéfini, insertion d'un fichier", "Imprimer"], exercices: ["Pratique saisie style (P9)", "Pratique la touche Tab (P10)", "Exercice 2 (P10)", "Exercice 3A (P11)", "Exercice 3B (P13)", "Exercice 3C (P14)", "Exercice 3D (P14)", "Exercice 4 (P14)", "Exercice 5 (P15)", "Évaluation chapitre 2"] },
  { titre: "3e chapitre : (Page 16 à 20)", points: ["SAISIE ET MODIFICATION DE TEXTE", "Espace insécable, trait d'union insécable, trait d'union conditionnel", "Insertion de symbole, insertion de date, sélection de texte", "COMMANDES DE BASE", "Passer d'un document à l'autre", "Conversion des majuscules/minuscules", "Correction d'orthographe, enregistrer en format PDF", "Enregistrer avec protection"], exercices: ["Pratique trait d'union conditionnel (P16)", "Exercice 6 (P17)", "Pratique gramm. ortho. corrigé (P18)", "Exercice 7 (P19)", "Questionnaire A (P20)", "Évaluation chapitre 3 (P20)"] },
  { titre: "4e chapitre : (Page 21 à 33)", points: ["LES CORRECTIONS, COPIER, COUPER, COLLER", "Correction automatique", "Copier, couper et coller"], exercices: ["Exercice 8 (P22)", "Exercice 9 (P23)", "Exercice 10 (P24)", "Exercice 11 (P25)", "Exercice 12 (P26)", "Exercice 13 (P26)", "Questionnaire B (P27)", "Évaluation chapitre 4"] },
  { titre: "5e chapitre : (Page 24 à 35)", points: ["MISE EN FORME DES CARACTÈRES, STYLES", "Vos attributs (groupe police)", "Surbrillance (surligneur), empattement", "Espacement des caractères, effet de texte, style", "Reproduire la mise en forme", "Rechercher mise en forme similaire"], exercices: ["Pratique mise en forme (P30)", "Exercice 14 (P31)", "Exercice 15 (P31)", "Exercice 16 (P32)", "Exercice 17 (P33)", "Exercice 18 (P34)", "Questionnaire C (P35)", "Évaluation chapitre 5"] },
  { titre: "6e chapitre : (Page 36 à 45)", points: ["AFFICHAGE ET IMPRESSION", "Aperçu avant impression, impression pages précises", "Mode d'affichage et navigation", "MISE EN PAGE", "Les marges, format du papier, orientation du papier", "Fin de ligne", "Page de garde", "SECTIONS ET TABLE DES MATIÈRES", "Sections, différentes sections", "Alignement vertical", "Mise en page d'un document divisé en sections", "Table des matières, style 4 et plus"], exercices: ["Exercice 19 (P37)", "Exercice 20 (P39)", "Pratique section (P40)", "Exercice 21 (P42)", "Exercice 22 (P43)", "Exercice 23 (P44)", "Questionnaire D (P45)", "Évaluation chapitre 6"] },
  { titre: "7e chapitre : (Page 46 à 50)", points: ["TABULATIONS", "Unité de mesure, tabulation, poser une tabulation à partir de la règle", "Supprimer une tabulation, tabulation avec point de suite"], exercices: ["Exercice 24-a (P47)", "Exercice 24-b (P48)", "Exercice 25 (P49)", "Exercice 26 (P50)", "Évaluation chapitre 7"] },
  { titre: "8e chapitre : (Page 51 à 57)", points: ["EN-TÊTE ET PIED DE PAGE", "Créer un en-tête", "Numérotation des pages", "Créer un pied de page", "En-tête et pied de page avec saut de section", "Changer de numérotation", "Imprimer une section de votre document"], exercices: ["Pratique en-tête (P51)", "Pratique pagination 1 (P53)", "Exercice 27 (P54)", "Pratique pagination 2 (P55)", "Exercice 28 (P55)", "Exercice 29 (P56)", "Questionnaire E (P57)", "Évaluation chapitre 8"] },
  { titre: "9e chapitre : (Page 58 à 62)", points: ["NUMÉROTATION ET LISTE À PUCES", "Création de listes simples", "Puces automatiques, personnalisation d'une liste", "Déplacer les puces, texte avant numérotation"], exercices: ["Pratique puce (P58)", "Exercice 30 (P59)", "Exercice 31 (P60)", "Exercice 32 (P61)", "Questionnaire F (P62)", "Évaluation chapitre 9"] },
  { titre: "10e chapitre : (Page 63 à 74)", points: ["MISE EN FORME DES PARAGRAPHES", "Les retraits de paragraphe", "Les interlignes", "Éviter veuve et orpheline, paragraphes solidaires, lignes solidaires", "BORDURE ET TRAME DE FOND", "Bordure de paragraphe", "Distancer le texte de la bordure", "Trame de fond", "BORDURES DE PAGE"], exercices: ["Exercice 33 (P65)", "Exercice 34 (P66)", "Pratique bordure (P68)", "Exercice 35 (P68-69)", "Exercice 36 (P69)", "Exercice 37 (P71)", "Exercice 38 (P73)", "Questionnaire G (P74)", "Évaluation chapitre 10"] },
  { titre: "11e chapitre : (Page 75 à 79)", points: ["INSERTION D'IMAGE ET FILIGRANE", "Insertion d'image, modification de l'image", "Insertion de forme, insertion d'un WordArt", "Filigrane", "Insérer une zone de texte"], exercices: ["Exercice 39 (P77)", "Pratique filigrane (P78)", "Pratique zone de texte (P78)", "Exercice 40 (P79)", "Exercice 41 (P79)", "Évaluation chapitre 11"] },
  { titre: "12e chapitre : (Page 80 à 82)", points: ["RECHERCHE ET REMPLACEMENT", "Recherche", "Remplacement"], exercices: ["Pratique recherche (P80)", "Exercice 42 (P81)", "Pratique chapitre 12"] },
  { titre: "13e chapitre : (Page 82 à 83)", points: ["ENVELOPPES ET ÉTIQUETTES", "Enveloppes", "Étiquettes"], exercices: ["Pratique enveloppe (P82)", "Pratique étiquettes (P83)"] },
  { titre: "14e chapitre : (Page 84 à 85)", points: ["INDEX", "Créer un index", "Marquer des entrées", "Supprimer un index"], exercices: [] },
  { titre: "15e chapitre : (Page 86)", points: ["MODÈLES DE LETTRES, STYLES DE LETTRES", "Style de lettre"], exercices: ["Pratique lettre (P86)"] },
  { titre: "16e chapitre : (Page 87)", points: ["CRÉATION ET MODIFICATION DES TABLEAUX", "Insérer tableau", "Outils de tableau"], exercices: [] },
];
